In [165]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [166]:
car=pd.read_csv('/content/quikr_car.csv')

In [167]:
car

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [168]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [169]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

year had many non-year values and then obj -> int

In [170]:
car=car[car['year'].str.isnumeric()]

In [171]:
car['year']=car['year'].astype(int)

/tmp/ipykernel_9207/152728128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['year']=car['year'].astype(int)

In [172]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [173]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

remove ask for price and the obj->int

In [174]:
car = car[car['Price'] != 'Ask For Price']

In [175]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [176]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

remove kms and obj->int

In [177]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [178]:
car=car[car['kms_driven'].str.isnumeric()]

In [179]:
car['kms_driven']=car['kms_driven'].astype(int)

In [180]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

fuel type has nan values

In [181]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [182]:
car=car[~car['fuel_type'].isna()]

In [183]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [184]:
car=car.reset_index(drop=True)

In [185]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [186]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [187]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [188]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [189]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [190]:
car.to_csv("cleaned_car.csv")

Model

In [191]:
x=car[['name','company','year','kms_driven','fuel_type']]
y=car['Price']

In [192]:
x

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [193]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int64

In [194]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [195]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [196]:
ohe=OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [197]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

linear_model

In [198]:
model=LinearRegression()

In [199]:
pipe=make_pipeline(column_trans,model)

In [200]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [201]:
y_pred=pipe.predict(x_test)

In [202]:
y_test

209    580000
419    500000
690    240000
125    299000
351    501000
        ...
808    250000
632    270000
305    584999
573    360000
692    260000
Name: Price, Length: 163, dtype: int64

In [203]:
r2_score(y_test,y_pred)

0.5647984046070509

In [208]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    print(r2_score(y_test,y_pred),i)

0.6397393260862305 0
0.570771233884424 1
0.6118751640380096 2
0.47535575298203225 3
0.7936529538155321 4
0.604274314543491 5
0.4448199348581878 6
0.5204364990233821 7
0.5444954927180101 8
0.645416040947811 9
0.6669258867577037 10
0.6570283974941824 11
0.46024039484363 12
0.5970352815900192 13
0.6793946729823909 14
0.5986609071827727 15
0.46920671558006044 16
0.6711463460844941 17
0.5748790589495013 18
0.7054540173861621 19
0.7178687127557679 20
0.38737692380920574 21
0.6500779080386432 22
0.5752042877589805 23
0.4575956823629541 24
0.4733022300284232 25
0.7341232939207466 26
0.7364859464455498 27
0.6978881866517213 28
0.5960922754152242 29
0.6767723618534136 30
0.8446868741108285 31
0.7439797623733405 32
0.758555107722585 33
0.6369474753758306 34
0.797820809376347 35
0.4808097667333572 36
0.48554200464901054 37
0.4879162417233228 38
0.7621654706280862 39
0.4196818590230139 40
0.6947711427125478 41
0.4849845121030534 42
0.5154169207020549 43
0.6071233091788939 44
0.7119555029420425 45
0.47066774787690624 46
0.47208983929914816 47
0.7680567800379932 48
0.7720827559540476 49
0.47896604943217325 50
0.6154219858166023 51
0.7811296526708461 52
0.7611089743654591 53
0.5601752395824733 54
0.7776340645325156 55
0.8599219372240148 56
0.7500336657452551 57
0.71506225898441 58
0.25489097169672725 59
0.4902148695847426 60
0.5198422039510873 61
0.47496791186547427 62
0.6848912091524789 63
0.5234201697692302 64
0.526916326441194 65
0.5824052183115205 66
0.6317851331745071 67
0.7632049784495658 68
0.7404260421244366 69
0.7513093659200523 70
0.756694957316315 71
0.5964838414674987 72
0.72066665826566 73
0.5306887536263138 74
0.6329229754848801 75
0.5344656391585669 76
0.7349419414770246 77
0.4759692607613686 78
0.6920891067361614 79
0.43884879367704055 80
0.41434602736718185 81
0.6209700323530141 82
0.7903982411899155 83
0.7887108803629206 84
0.6537336151613093 85
0.7076279514568646 86
0.4868583169416586 87
0.6275911887799777 88
0.5995636323100266 89
0.7060112033794697 90
0.5792743906053794 91
0.7198044680511901 92
0.5838815967555702 93
0.59159579116974 94
0.6474171275787912 95
0.6651487028445726 96
0.7205826437667935 97
0.5986380484648883 98
0.6144618160906088 99
0.7398983801135685 100
0.6449413768894807 101
0.7177516243422728 102
0.701677567070206 103
0.6568357718274913 104
0.6440564781010589 105
0.4413900884996147 106
0.4688416940990262 107
0.5133760525701739 108
0.755905382052111 109
0.812028093728209 110
0.6669431211051463 111
0.4959960375946447 112
0.7415948184977041 113
0.5284393018742094 114
0.5744353224393726 115
0.6310277434507761 116
0.6122328181174663 117
0.496702443194992 118
0.7437904580239213 119
0.7319469898840028 120
0.6520196462748169 121
0.7440569617279138 122
0.6403620865846412 123
0.7268613992268764 124
0.6015739109557058 125
0.7518697588154764 126
0.8445199669304794 127
0.5272128085214176 128
0.5488645183284281 129
0.5914251085919593 130
0.5967366490598597 131
0.5884816294430135 132
0.6257988514166936 133
0.7143440898835667 134
0.8569962512391454 135
0.5226412812429724 136
0.6736248964306368 137
0.5646469722123002 138
0.7227113454594576 139
0.5966757064520605 140
0.5593395037020712 141
0.7454261709573113 142
0.34302975699642657 143
0.716088262721122 144
0.7140255132959217 145
0.7079109955559375 146
0.49818149397479694 147
0.5105893275426405 148
0.5710140221395132 149
0.45020802290315465 150
0.8110064191877924 151
0.5738895486479638 152
0.4822312179326099 153
0.696321936365965 154
0.5901693622997568 155
0.3616660604291452 156
0.815214941015786 157
0.5890639327495653 158
0.6824737870563315 159
0.5731261171810387 160
0.47552674156964436 161
0.6547475315795849 162
0.4709230593785766 163
0.5866991547382105 164
0.6265773597966419 165
0.7469897323330945 166
0.7275048331802862 167
0.4581459646901498 168
0.7214963464234537 169
0.8017557753637673 170
0.8082234926234613 171
0.8276319979983267 172
0.7739148138007544 173
0.5156138806482218 174
0.18200395843417239 175
0.6854350085377425 176
0.592772661678972 177
0.6749832336449488 178
0.64222572467283 179
0.638078969521688 180
0.6041766872595145 181
0.6238039682934893 182
0.611966095913477 183
0.6062532701611172 184
0.6992689420885934 185
0.6566126936925465 186
0.66401526353834 187
0.6958718838121658 188
0.5581661428373901 189
0.7840363103517285 190
0.677428668817672 191
0.7502520607740313 192
0.6725756279358853 193
0.7149867182854688 194
0.46463431963171753 195
-0.10275114864308343 196
0.6694282268521417 197
0.4672783290954121 198
0.6292698654756508 199
0.6514531470328 200
0.4692252026149253 201
0.5362424374670378 202
0.7422704844919672 203
0.6030749413773548 204
0.6151659707884265 205
0.7235605799079912 206
0.5733789967913611 207
0.6797262014224494 208
0.5317940982749627 209
0.5108891030384617 210
0.5936092603880001 211
0.595847337866654 212
0.6640097443867472 213
0.6571537624494355 214
0.4788362757841814 215
0.5838714428221912 216
0.5796599349600668 217
0.6633973620122177 218
0.7374354168690629 219
0.6325620656864729 220
0.678138417078393 221
0.495013805784447 222
0.4467230852874786 223
0.4600540684154587 224
0.7383219695659355 225
0.7011248908558894 226
0.6608710441266845 227
0.6744820307470372 228
0.5058734935700491 229
0.5047400983498507 230
0.5703460790761319 231
0.5408820415096488 232
0.5912165619671622 233
0.8128167322885479 234
0.7703998214395218 235
0.8407511651106654 236
0.6919429528788623 237
0.43272360523224984 238
0.5719956139980644 239
0.7087443258220683 240
0.357152431169936 241
0.5818998151516749 242
0.7557920141363728 243
0.5280560700611612 244
0.7526836945225113 245
0.7824723458469712 246
0.8235182564612141 247
0.7652802308324372 248
0.27216741902940644 249
0.46443962891823176 250
0.36939803203530275 251
0.4317424474465257 252
0.6919344793208202 253
0.682268568460874 254
0.7685948849616249 255
0.5503089858047441 256
0.5397781578800855 257
0.552382496656439 258
0.408115814398447 259
0.7765529922013129 260
0.6698304506199351 261
0.8072759209166944 262
0.7252351889159572 263
0.5009071452213272 264
0.4221845720253945 265
0.6870927798608975 266
0.6163913330465202 267
0.5430067136038428 268
0.4227156924022758 269
0.5724980373631889 270
0.6005991664011088 271
0.7281375954160062 272
0.6401159164331602 273
0.6218217203366441 274
0.5328945067807165 275
0.6530595105992785 276
0.6008147281259859 277
0.7635284978628879 278
0.7587524272100404 279
0.5657668119747115 280
0.6950688491914166 281
0.6648177852779118 282
0.6628422070740732 283
0.7833952581818052 284
0.4781118436070063 285
0.777935177227387 286
0.6187485581210062 287
0.41415643153498727 288
0.6116882879917365 289
0.5838143994597926 290
0.5976223898987882 291
0.766999445777949 292
0.7381961092411707 293
0.8295124970502293 294
0.500988188831086 295
0.7078299755958938 296
0.698403968124522 297
0.6689593056690784 298
0.6785595295395941 299
0.7351788063405409 300
0.662622990512898 301
0.8991157554877304 302
0.5799841261434588 303
0.7715218635613798 304
0.6063385862565935 305
0.7417951769941649 306
0.6881749431574367 307
0.5274887067295924 308
0.7157454725762209 309
0.7632304588659501 310
0.6971745352904282 311
0.36925749249540896 312
0.41374368135298256 313
0.5175831456614111 314
0.7201023204469159 315
0.5522975709934985 316
0.48183798139203626 317
0.5607465913437482 318
0.6156295492413804 319
0.5732352254305363 320
0.7677771126772132 321
0.47372813090457466 322
0.5740890636818546 323
0.5560487870319928 324
0.5712041313577245 325
0.6692238388267358 326
0.5523322780200177 327
0.641161704592915 328
0.562950467511105 329
0.6124125300283785 330
0.6743015050844061 331
0.6323652665009731 332
0.5190675231617362 333
0.7126015847192391 334
0.5773338691684788 335
0.4854135168759379 336
0.666465333307756 337
0.7559488151324109 338
0.5322755824608505 339
0.6735242274096971 340
0.7274476686702003 341
0.7832872775431067 342
0.6878405240798174 343
0.6113711636278529 344
0.6881415848416714 345
0.627966305692854 346
0.5461079249106919 347
0.48537010571661154 348
0.644265958672045 349
0.6553702467291835 350
0.645253181615078 351
0.8304493073031265 352
0.42566090489592967 353
0.6681401813176042 354
0.6454838434335245 355
0.6186183224840827 356
0.6803157793623424 357
0.6856193929404983 358
0.6246006917440017 359
0.6558977549538864 360
0.5424225119846304 361
0.44347702486006313 362
0.7136249876259968 363
0.7212159544285546 364
0.6775130537530663 365
0.7663148748175067 366
0.4260795960414827 367
0.7273678667961427 368
0.7745378323846721 369
0.7112070415687903 370
0.4669872928238896 371
0.5033661283254229 372
0.6521161885038999 373
0.3706267385740032 374
0.584561757390458 375
0.6440717114343719 376
0.5840402703536023 377
0.8034798063568689 378
0.7501492961446208 379
0.49128917015878426 380
0.777514878507723 381
0.6939739177329531 382
0.8445054339549046 383
0.6831148117256385 384
0.6844189370255735 385
0.7251663922665179 386
0.4762913305006544 387
0.5297185486038882 388
0.4190985700262696 389
0.7885161414145679 390
0.6611427843236447 391
0.8176080153656801 392
0.5382700833913766 393
0.5886719681958918 394
0.6874808489020087 395
0.5453869353048134 396
0.5892827286991864 397
0.49538082404958894 398
0.7116506932698397 399
0.593345023031935 400
0.6499958908340739 401
0.7653650664699245 402
0.4383633088647827 403
0.7429084000273289 404
0.18552345626719036 405
0.540864861884444 406
0.7031478989948854 407
0.6999866097953918 408
0.6359377012627496 409
0.7067726328473574 410
0.6664426331536564 411
0.6532877433857555 412
0.6812868738890185 413
0.7289412743652548 414
0.6058820274029235 415
0.637557714905848 416
0.750421148576111 417
0.650737764812167 418
0.6167797005306545 419
0.7138414796651753 420
0.6785919514117082 421
0.6373285633002069 422
0.45586803539191456 423
0.6660855632090483 424
0.5584891380591419 425
0.4271851696147302 426
0.7705567984046668 427
0.537835876504986 428
0.7790559529790011 429
0.6322622206741375 430
0.8231935533214919 431
0.7331574132297619 432
0.7879819993060558 433
0.4670644931590684 434
0.7608446431038609 435
0.5330453609525831 436
0.5717740491455687 437
0.5465076226927379 438
0.7427986567286033 439
0.6653956291566789 440
0.645632725237358 441
0.7980964629219169 442
0.7613143530958483 443
0.768031358036712 444
0.6415088831002862 445
0.737938926481672 446
0.6433650950788199 447
0.6325023676402355 448
0.7002775147461209 449
0.6277501274249367 450
0.5371281913519812 451
0.7442615221966187 452
0.596166901348696 453
0.5749474224145154 454
0.6721396794003173 455
0.3542665166458625 456
0.4085196253633677 457
0.711634228320768 458
0.6706836284833447 459
0.7359625138866699 460
0.48767366122252054 461
0.667899261239208 462
0.8690002684295676 463
0.4218759385116352 464
0.6489490098003031 465
0.4707209320586473 466
0.6513598539925272 467
0.6641654052005301 468
0.576064289223631 469
0.6260265643048812 470
0.4355633880451171 471
0.2521538434011783 472
0.5150573203998565 473
0.7042889618227257 474
0.7108450761871755 475
0.5531142052033517 476
0.6762197980011566 477
0.7831917860423513 478
0.5423660812170625 479
0.6890340629631007 480
0.5966338235994437 481
0.7830221574190307 482
0.7432280706803234 483
0.6995866972115389 484
0.6549106246306713 485
0.5705245797350789 486
0.5390419128708284 487
0.7672483140736008 488
0.6360329582864926 489
0.4591454358051855 490
0.7728244613617258 491
0.6543849368861842 492
0.5102419573598995 493
0.6094407694839039 494
0.5281861597347951 495
0.66191561668166 496
0.5900324871024413 497
0.6685825624997181 498
0.8451632830554114 499
0.656739059057748 500
0.5970614418533084 501
0.674022831232364 502
0.687105183264407 503
0.6716383394115819 504
0.6003268924763301 505
0.5311860627806184 506
0.8544779333334802 507
0.6112794350473127 508
0.6491126876149197 509
0.6810787711952491 510
0.8456499802020283 511
0.663191724637292 512
0.7451762773520774 513
0.6400693739124697 514
0.8245599262852235 515
0.7361330995529347 516
0.7350445223690201 517
0.5941798048393172 518
0.6962322775783268 519
0.7593445527862475 520
0.6183287608552257 521
0.6718513932801948 522
0.5621286309603081 523
0.7266300077581405 524
0.4009164174902349 525
0.7196561279253008 526
0.6313088762483259 527
0.7980623777643849 528
0.6222008677069403 529
0.6169266684410669 530
0.4992962870773374 531
0.5995686082500362 532
0.7278432608039556 533
0.6692572363220696 534
0.7234968988169025 535
0.5299366294867982 536
0.6988571524819511 537
0.6929377694891165 538
0.6156982797598946 539
0.6855601858642384 540
0.516147660677147 541
0.7035384855887439 542
0.7382454769599445 543
0.6517168248649712 544
0.46228095794007895 545
0.7248509434069943 546
0.4154225656327962 547
0.637300704138359 548
0.4128201632870029 549
0.5571728576886086 550
0.8106675461134496 551
0.7253686059492002 552
0.7924793544028739 553
0.6076568342485831 554
0.6913132271240141 555
0.4389441934174402 556
0.5432868023721769 557
0.7006050193241695 558
0.6192332556078615 559
0.5476438394249192 560
0.46587290747428023 561
0.7211093749510444 562
0.3580534446737923 563
0.5952395462213868 564
0.6252599999860231 565
0.7708161198267047 566
0.612610076453947 567
0.7897020131877996 568
0.4724253297383849 569
0.5946053439322423 570
0.712611173783577 571
0.6090903971286139 572
0.6302787487609787 573
0.7506403022006906 574
0.7485653641131218 575
0.7364876806229836 576
0.6557840075970335 577
0.464457602088718 578
0.5480283897069235 579
0.5372565603187536 580
0.7443516365310897 581
0.43895504446610933 582
0.7933731550195551 583
0.4175973971909177 584
0.5094848608918744 585
0.831771474099773 586
0.7535576285122161 587
0.7505084901508401 588
0.7310428937444258 589
0.7374924013612036 590
0.6344615387419927 591
0.8131292993051903 592
0.749519830150538 593
0.6620394770215137 594
0.2760046925913938 595
0.519537870497715 596
0.40021083611840735 597
0.7405582543380114 598
0.45024859934673767 599
0.48423122911505156 600
0.7244502812212348 601
0.7209438752203008 602
0.6634906021998743 603
0.46271377798597335 604
0.7914304351014574 605
0.4742533798987838 606
0.6983550998866134 607
0.7445257446702773 608
0.6459271872099466 609
0.42350959152348266 610
0.40285205985119865 611
0.5836694014206681 612
0.6038851463273125 613
0.7266809560873422 614
0.7233653929090306 615
0.4307237370404531 616
0.6322374011068002 617
0.613630406383623 618
0.5271431256706889 619
0.5764319390689986 620
0.6586176716157516 621
0.5480686046735919 622
0.6725324121921439 623
0.8164192162801582 624
0.4624488908232003 625
0.4390721582272129 626
0.4975763355821894 627
0.6437872368358261 628
0.6276809561460662 629
0.5882935337971391 630
0.5984694190342578 631
0.7052874407425116 632
0.6584073817761321 633
0.2914883435188692 634
0.6924320955541375 635
0.873603798616331 636
0.6753402940509161 637
0.7605853160428044 638
0.7172787379601728 639
0.5792373313348402 640
0.6010248379846699 641
0.604009762846409 642
0.6454260922719095 643
0.4050263986454944 644
0.6985128502313138 645
0.6692756441054655 646
0.6080316357975436 647
0.7535514769270678 648
0.8103767920165008 649
0.6589983705535036 650
0.4602195477092149 651
0.7349483043487381 652
0.7307485282769577 653
0.532045697945243 654
0.8666546807704116 655
0.6513307427992896 656
0.4705024414383905 657
0.6659597118920231 658
0.7003435848996169 659
0.5359539400659702 660
0.7234854442051242 661
0.5241512990793424 662
0.538670430329641 663
0.5290443592337776 664
0.5169506313126859 665
0.6812579427606074 666
0.7254294112492073 667
0.7249048268848156 668
0.7346109314135684 669
0.747769872658613 670
0.6187995084962399 671
0.6182987009391728 672
0.6783769892159267 673
0.5845879496841605 674
0.660977312845655 675
0.6086784042033238 676
0.5283829368680657 677
0.7998619704360144 678
0.6117609487013294 679
0.7232348736982379 680
0.5478720977541423 681
0.7447027167063336 682
0.6588906117622035 683
0.5685633527223992 684
0.6144707576754349 685
0.8262163998315643 686
0.6391126359756547 687
0.5597161452717561 688
0.7556838168171468 689
0.6590398866462233 690
0.6978754200698627 691
0.716339287243638 692
0.6673538069175368 693
0.7328286698540076 694
0.7086210359246572 695
0.7221471639947699 696
0.6130465353664705 697
0.7478809434033016 698
0.6737886555562657 699
0.4735521897350192 700
0.7107211136766711 701
0.5649025159337051 702
0.7628918957728945 703
0.5356798026227005 704
0.6270568713783085 705
0.6035474815828344 706
0.5599648389070861 707
0.5512944398909259 708
0.338377761968626 709
0.5873211699356595 710
0.7588879927036424 711
0.7977621746890987 712
0.7688354836964684 713
0.45296825389880024 714
0.7102324174084103 715
0.7796467479526523 716
0.5597054657521512 717
0.43591870921920517 718
0.6617822709544368 719
0.4791312015837802 720
0.6050749190497903 721
0.7074488563475081 722
0.7961374140389083 723
0.6526342959222939 724
0.48768174917263396 725
0.6504475404711778 726
0.6667486493040717 727
0.5373924156713935 728
0.7597176304754073 729
0.625069914533477 730
0.7190594643813919 731
0.7966799674695245 732
0.6020590950790538 733
0.5213266927124818 734
0.4011964882048802 735
0.7025699431339579 736
0.5420684495312058 737
0.5495774784508239 738
0.5523965955691913 739
0.7258556002092933 740
0.6087278775713164 741
0.6726867161046938 742
0.7333956287413105 743
0.5724454048474503 744
0.6378087301924003 745
0.7464843207067371 746
0.5198863291295643 747
0.4808837917176736 748
0.41523910843771306 749
0.5603068144988503 750
0.7073808288478164 751
0.6816546312851153 752
0.7152655651630149 753
0.663402902632582 754
0.5810393491909749 755
0.45888901502405455 756
0.7087996248979255 757
0.6267847375451367 758
0.5189603079878958 759
0.6652730766434478 760
0.7207222751914375 761
0.7179060166095584 762
0.5736895785481653 763
0.6935672797755681 764
0.5743174166589942 765
0.6279566497373676 766
0.5983518797707104 767
0.40938677665452217 768
0.7682471913189189 769
0.5143055091332058 770
0.6381324966502404 771
0.7492980593365476 772
0.6401785639540285 773
0.4914353709176663 774
0.5288468423683224 775
0.6034165447477489 776
0.48859909115000066 777
0.7352838404152852 778
0.5820243188512839 779
0.7421479001753495 780
0.7764844535985491 781
0.719779112453647 782
0.8182954267607012 783
0.6846995101149533 784
0.4983483967624339 785
0.6442811444829927 786
0.558564164498047 787
0.5077701420847748 788
0.415252093997834 789
0.8004759420704042 790
0.7255941720566321 791
0.7605334640065288 792
0.7410743930034831 793
0.6527388369934033 794
0.7242206741968988 795
0.7602866271042338 796
0.4754140433371655 797
0.39213492124931626 798
0.6521104696691429 799
0.5845370371441245 800
0.43967872054983326 801
0.688504914338516 802
0.6550011984061853 803
0.7953518046313479 804
0.6893922534114318 805
0.6642054581974418 806
0.826190586138425 807
0.4113149495631546 808
0.6937839713686322 809
0.4558853028174197 810
0.6074490089649396 811
0.6697959058830745 812
0.5852007805525454 813
0.8306350830314928 814
0.4817420197229886 815
0.6331455115951704 816
0.8372905114944345 817
0.7201104133523718 818
0.5550872257606116 819
0.6876489254317524 820
0.6382233820993948 821
0.7239449547942584 822
0.7208343512820755 823
0.4370220308257029 824
0.6761045410370472 825
0.62635304589888 826
0.5738223483104496 827
0.5037315943515186 828
0.6284789939557948 829
0.4516473595326399 830
0.6540390282588056 831
0.8142708307136124 832
0.5427330980429252 833
0.710530575039072 834
0.6091707384056503 835
0.6787051445884513 836
0.6060492958645061 837
0.4944143405802416 838
0.6728418440598252 839
0.7230911537529978 840
0.8456671785672414 841
0.7274268834306312 842
0.7249086401223335 843
0.6451621576587518 844
0.748647306626883 845
0.5885420730945468 846
0.6268736096876333 847
0.7651248510996703 848
0.7030741346118594 849
0.7320197144365026 850
0.7442239678022853 851
0.6488098608272164 852
0.7019622541390951 853
0.7266640392083112 854
0.622189887101974 855
0.4490991551089092 856
0.43253396224577767 857
0.7680140934878799 858
0.5132972941573961 859
0.681013241484652 860
0.6757569804311503 861
0.5442769689798834 862
0.6848762571891749 863
0.6215654050222155 864
0.28214141295997563 865
0.6082957352174292 866
0.563002584272797 867
0.6152236085330887 868
0.6578131230668885 869
0.5899554208444366 870
0.6567928586775373 871
0.7280562073735755 872
0.6423196427422887 873
0.8263053249077023 874
0.7256960980068383 875